version: '2.1'

services:
  postgres:
    container_name: "my-postgres"
    build: postgres
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: "dykn"
      POSTGRES_PASSWORD:

  redis:
    container_name: "my-redis"
    image: redis:3.2
    ports:
      - "6379:6379"
